# Generated by Django 4.2.7 on 2023-11-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('comment_user', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                # ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
